# Generated by Django 4.2.18 on 2025-03-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polloption',
            name='poll',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vote',
            name='poll_option',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='blog_audio/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='has_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollOption',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
